In [101]:
import pandas as pd 


df = pd.read_csv("listings.csv")
print(df)

                       id                                      listing_url  \
0      579652405189065070  https://www.airbnb.com/rooms/579652405189065070
1                49797548            https://www.airbnb.com/rooms/49797548
2                  218103              https://www.airbnb.com/rooms/218103
3                 1117474             https://www.airbnb.com/rooms/1117474
4                 1136724             https://www.airbnb.com/rooms/1136724
...                   ...                                              ...
10880  591221838086690180  https://www.airbnb.com/rooms/591221838086690180
10881            50594474            https://www.airbnb.com/rooms/50594474
10882  556379338554707629  https://www.airbnb.com/rooms/556379338554707629
10883            16789721            https://www.airbnb.com/rooms/16789721
10884  678024184489558143  https://www.airbnb.com/rooms/678024184489558143

            scrape_id last_scraped           source  \
0      20220912200234   2022-09-12      city scrape
1      20220912200234   2022-09-12      city scrape
2      20220912200234   2022-09-13      city scrape
3      20220912200234   2022-09-13      city scrape
4      20220912200234   2022-09-12      city scrape
...               ...          ...              ...
10880  20220912200234   2022-09-13  previous scrape
10881  20220912200234   2022-09-13      city scrape
10882  20220912200234   2022-09-13      city scrape
10883  20220912200234   2022-09-13  previous scrape
10884  20220912200234   2022-09-13  previous scrape

                                                   name  \
0      Appartement cosy dans centre historique de Bourg
1        Maison de vacances entre Bordeaux et le Bassin
2                    B&B Apart.Suite  / tropical garden
3                          INCROYABLE T3 EN HYPERCENTRE
4         Spacious house, 4 guests with Garden & Garage
...                                                 ...
10880  Maison chaleureuse avec piscine près de Bordeaux
10881                            Le clos des vignes****
10882           escale gourmande au coeur des vignobles
10883     Logement aux portes de Bordeaux et de l'océan
10884        Jolie maison familiale avec jardin paysagé

                                             description  \
0      Dans le centre historique de Bourg, idéalement...
1      Villa moderne idéalement située entre Bordeaux...
2      <b>The space</b><br />The Bambooyard  : "Le cl...
3      <b>The space</b><br />In the heart of the hist...
4      BOOK A STREET ART HOUSE! Cozy, colorful and cl...
...                                                  ...
10880  Bienvenue dans notre maison ! <br />C'est notr...
10881  À 20 minutes de Bordeaux et à 3 minutes des so...
10882  studio independant comportant:<br /><br /> une...
10883  Situé au départ de la route des châteaux, à 10...
10884  Notre maison familiale se situe dans un lotiss...

                                   neighborhood_overview  \
0      Vous vous situez dans le centre historique de ...
1      Ballades à pied ou à vélo dans la foret: 5 vél...
2                                                    NaN
3                                                    NaN
4                                                    NaN
...                                                  ...
10880  Nous sommes situés à 20 min de la gare de bord...
10881                                                NaN
10882  quartier calme ambiance vigne et campagne à 2 ...
10883                                     Quartier calme
10884  Notre maison se trouve dans un petit lotisseme...

                                             picture_url    host_id  ...  \
0      https://a0.muscache.com/pictures/miso/Hosting-...   15134863  ...
1      https://a0.muscache.com/pictures/miso/Hosting-...   83677621  ...
2      https://a0.muscache.com/pictures/9ba23c8f-4780...    1127981  ...
3      https://a0.muscache.com/pictures/20359851/80f7...    6133211  ...
4      https://a0.muscache.com/pictures/b876925a-2b69...    3774373  ...
...                                                  ...        ...  ...
10880  https://a0.muscache.com/pictures/miso/Hosting-...    5220890  ...
10881  https://a0.muscache.com/pictures/miso/Hosting-...  408562043  ...
10882  https://a0.muscache.com/pictures/6349e9f7-cdce...   62440676  ...
10883  https://a0.muscache.com/pictures/miso/Hosting-...  111565429  ...
10884  https://a0.muscache.com/pictures/miso/Hosting-...   23002270  ...

      review_scores_communication review_scores_location review_scores_value  \
0                            5.00                   5.00                4.93
1                            5.00                   5.00                5.00
2                            4.96                   4.57                4.54
3                            4.88                   4.93                4.80
4                            4.91                   4.62                4.70
...                           ...                    ...                 ...
10880                         NaN                    NaN                 NaN
10881                        4.95                   4.74                4.83
10882                        4.77                   4.73                4.64
10883                        5.00                   4.88                4.88
10884                         NaN                    NaN                 NaN

             license instant_bookable calculated_host_listings_count  \
0                NaN                t                              1
1                NaN                f                              1
2                NaN                f                              4
3      330630009852A                f                              1
4      33063003349C9                t                              4
...              ...              ...                            ...
10880            NaN                t                              1
10881            NaN                f                              2
10882            NaN                t                              3
10883            NaN                t                              1
10884            NaN                f                              1

      calculated_host_listings_count_entire_homes  \
0                                               1
1                                               1
2                                               4
3                                               1
4                                               4
...                                           ...
10880                                           1
10881                                           2
10882                                           2
10883                                           1
10884                                           1

      calculated_host_listings_count_private_rooms  \
0                                                0
1                                                0
2                                                0
3                                                0
4                                                0
...                                            ...
10880                                            0
10881                                            0
10882                                            1
10883                                            0
10884                                            0

      calculated_host_listings_count_shared_rooms reviews_per_month
0                                               0              2.74
1                                               0              0.21
2                                               0              0.44
3                                               0              3.31
4                                               0              4.36
...                                           ...               ...
10880                                           0               NaN
10881                                           0              5.73
10882                                           0              6.11
10883                                           0              0.26
10884                                           0               NaN

[10885 rows x 75 columns]

In [102]:
df.head(1)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,579652405189065070,https://www.airbnb.com/rooms/579652405189065070,20220912200234,2022-09-12,city scrape,Appartement cosy dans centre historique de Bourg,"Dans le centre historique de Bourg, idéalement...",Vous vous situez dans le centre historique de ...,https://a0.muscache.com/pictures/miso/Hosting-...,15134863,...,5.0,5.0,4.93,NaN,t,1,1,0,0,2.74

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10885 entries, 0 to 10884
Data columns (total 75 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            10885 non-null  int64
 1   listing_url                                   10885 non-null  object
 2   scrape_id                                     10885 non-null  int64
 3   last_scraped                                  10885 non-null  object
 4   source                                        10885 non-null  object
 5   name                                          10884 non-null  object
 6   description                                   10701 non-null  object
 7   neighborhood_overview                         6539 non-null   object
 8   picture_url                                   10885 non-null  object
 9   host_id                                       10885 non-null  int64
 10  host_url                                      10885 non-null  object
 11  host_name                                     10885 non-null  object
 12  host_since                                    10885 non-null  object
 13  host_location                                 9036 non-null   object
 14  host_about                                    4235 non-null   object
 15  host_response_time                            7032 non-null   object
 16  host_response_rate                            7032 non-null   object
 17  host_acceptance_rate                          7546 non-null   object
 18  host_is_superhost                             10881 non-null  object
 19  host_thumbnail_url                            10885 non-null  object
 20  host_picture_url                              10885 non-null  object
 21  host_neighbourhood                            3303 non-null   object
 22  host_listings_count                           10885 non-null  int64
 23  host_total_listings_count                     10885 non-null  int64
 24  host_verifications                            10885 non-null  object
 25  host_has_profile_pic                          10885 non-null  object
 26  host_identity_verified                        10885 non-null  object
 27  neighbourhood                                 6539 non-null   object
 28  neighbourhood_cleansed                        10885 non-null  object
 29  neighbourhood_group_cleansed                  10885 non-null  object
 30  latitude                                      10885 non-null  float64
 31  longitude                                     10885 non-null  float64
 32  property_type                                 10885 non-null  object
 33  room_type                                     10885 non-null  object
 34  accommodates                                  10885 non-null  int64
 35  bathrooms                                     0 non-null      float64
 36  bathrooms_text                                10876 non-null  object
 37  bedrooms                                      9861 non-null   float64
 38  beds                                          10754 non-null  float64
 39  amenities                                     10885 non-null  object
 40  price                                         10885 non-null  object
 41  minimum_nights                                10885 non-null  int64
 42  maximum_nights                                10885 non-null  int64
 43  minimum_minimum_nights                        10885 non-null  int64
 44  maximum_minimum_nights                        10885 non-null  int64
 45  minimum_maximum_nights                        10885 non-null  int64
 46  maximum_maximum_nights                        10885 non-null  int64
 47  minimum_nights_avg_ntm                        10885 non-null  float64
 48  maximum_nights_avg_ntm                        10885 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              10885 non-null  object
 51  availability_30                               10885 non-null  int64
 52  availability_60                               10885 non-null  int64
 53  availability_90                               10885 non-null  int64
 54  availability_365                              10885 non-null  int64
 55  calendar_last_scraped                         10885 non-null  object
 56  number_of_reviews                             10885 non-null  int64
 57  number_of_reviews_ltm                         10885 non-null  int64
 58  number_of_reviews_l30d                        10885 non-null  int64
 59  first_review                                  9245 non-null   object
 60  last_review                                   9245 non-null   object
 61  review_scores_rating                          9245 non-null   float64
 62  review_scores_accuracy                        9147 non-null   float64
 63  review_scores_cleanliness                     9149 non-null   float64
 64  review_scores_checkin                         9145 non-null   float64
 65  review_scores_communication                   9147 non-null   float64
 66  review_scores_location                        9145 non-null   float64
 67  review_scores_value                           9145 non-null   float64
 68  license                                       3806 non-null   object
 69  instant_bookable                              10885 non-null  object
 70  calculated_host_listings_count                10885 non-null  int64
 71  calculated_host_listings_count_entire_homes   10885 non-null  int64
 72  calculated_host_listings_count_private_rooms  10885 non-null  int64
 73  calculated_host_listings_count_shared_rooms   10885 non-null  int64
 74  reviews_per_month                             9245 non-null   float64
dtypes: float64(16), int64(23), object(36)
memory usage: 6.2+ MB

In [104]:
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [105]:
df_neighbourhood_cleansed = df[['host_id','number_of_reviews','neighbourhood_cleansed']]
df_neighbourhood_cleansed

         host_id  number_of_reviews                     neighbourhood_cleansed
0       15134863                 15                                       Ambs
1       83677621                  3                        Martignas-sur-Jalle
2        1127981                 58                                      Bgles
3        6133211                377                    Centre ville (Bordeaux)
4        3774373                491  Saint Augustin - Tauzin - Alphonse Dupeux
...          ...                ...                                        ...
10880    5220890                  0                      Artigues-Prs-Bordeaux
10881  408562043                 82                          Villenave-d'Ornon
10882   62440676                 44                          Villenave-d'Ornon
10883  111565429                 16                                 Parempuyre
10884   23002270                  0                                 Parempuyre

[10885 rows x 3 columns]

Calculez le nombre d’hosst et le nombre de review par quartier. (
neighbourhood_cleansed)?

In [106]:
df_neighbourhood_cleansed.groupby(by="neighbourhood_cleansed").count()

                        host_id  number_of_reviews
neighbourhood_cleansed
3M-Bourgailh                 10                 10
Ambars-et-Lagrave            69                 69
Ambs                         57                 57
Arago-La Chataigneraie       58                 58
Arlac                        98                 98
...                         ...                ...
Sardine                      21                 21
Talence                     494                494
Toctoucau                    18                 18
Verthamon                    26                 26
Villenave-d'Ornon           320                320

[62 rows x 2 columns]

Quels sont les pourcentage d’acceptation et de réponse moyen des hosts? (on ne tiendra pas comtpe des valeurs manquantes pour ce calcul) (calculez la moyenne au global pour toute la colonne, pas par host)

In [107]:
df_acce_rate =df['host_acceptance_rate']
df_reponse_rate =df['host_response_rate']
print(df_acce_rate )
print(df_reponse_rate)

0         99%
1        100%
2         95%
3         78%
4        100%
         ...
10880     NaN
10881     90%
10882    100%
10883    100%
10884     NaN
Name: host_acceptance_rate, Length: 10885, dtype: object
0        100%
1        100%
2         NaN
3        100%
4        100%
         ...
10880     NaN
10881    100%
10882    100%
10883    100%
10884     NaN
Name: host_response_rate, Length: 10885, dtype: object

In [108]:
df_acce_rate_clean=df_acce_rate.dropna()
df_reponse_rate_clean =df_reponse_rate.dropna()
print(df_acce_rate_clean, df_reponse_rate_clean)

0         99%
1        100%
2         95%
3         78%
4        100%
         ...
10878      0%
10879      0%
10881     90%
10882    100%
10883    100%
Name: host_acceptance_rate, Length: 7546, dtype: object 0        100%
1        100%
3        100%
4        100%
5        100%
         ...
10877     99%
10879    100%
10881    100%
10882    100%
10883    100%
Name: host_response_rate, Length: 7032, dtype: object

In [109]:
serie_acc =df_acce_rate_clean.str.rstrip('%').astype('float') / 100.0
serie_acc.mean()

0.8210151073416379

In [110]:
serie_reponse = df_reponse_rate_clean.str.rstrip('%').astype('float') / 100.0
serie_reponse.mean()

0.9348065984072811

Quel pourcentage des hosts on une vérification:
par téléphone
par email
par email pro

In [111]:
# df_verification= df[['host_id','host_verifications']]
# df_verification.pivot_table(df,valeur = 'host_verifications',index =['email', 'phone', 'work_email'] )

In [ ]:
df['host_verifications'].value_counts()

['email', 'phone']                  9287
['phone']                            820
['email', 'phone', 'work_email']     677
['email']                             45
[]                                    31
['phone', 'work_email']               24
['email', 'work_email']                1
Name: host_verifications, dtype: int64

In [130]:
serie_verification =df['host_verifications']
serie_length =serie_verification.size
serie_length

10885

In [127]:
serie_verification.

AttributeError: 'Series' object has no attribute 'length'

In [126]:
from ast import literal_eval

def pourcentage_moyen_vérification(df):
    serie_verification =df['host_verifications']
    serie_length =serie_verification.size
    n_email = 0
    n_telephone = 0
    n_work_email = 0

    for valitation in serie_verification:
        val = literal_eval(valitation)
        for ele in val:
            if ele == 'email':
                n_email+=1
            elif ele == 'phone':
                n_telephone+=1
            elif ele == 'work_email':
                n_work_email+=1
    pourcen_telephone = n_telephone/serie_length 
    pourcen_email = n_email/serie_length
    pourcen_work_mail = n_work_email/serie_length

    print("le pourcentage de validation par n_email\n n_telephone,n_work_email")

10010 10808 702